# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate Power for Bayesian RCT Using Beta-Binomial Conjugate Model (C++)
#'
#' Performs Monte Carlo simulation to estimate the statistical power of a
#' Bayesian randomized controlled trial (RCT) using conjugate Beta-Binomial
#' models for the control and treatment arms. The function supports flat priors
#' and power priors on the control arm, and allows for fully customizable
#' baseline Beta prior parameters for both arms.
#'
#' A trial is declared successful if the posterior probability
#' \eqn{Pr(\theta_t - \theta_c > M \mid \text{data}) \ge \gamma}.
#'
#' @param B Integer. Number of simulated trials.
#' @param p_c,p_t Numeric in \[0, 1\]. True response probabilities in the control and treatment arms.
#' @param n_c,n_t Integers. Sample sizes in the control and treatment arms.
#' @param M Numeric. Margin on the risk-difference scale:
#'   - Negative for non-inferiority,
#'   - Zero for equivalence,
#'   - Positive for superiority.
#' @param threshold Numeric in (0, 1). Posterior probability threshold \eqn{\gamma}.
#' @param prior Character. Type of prior to use:
#'   - `"flat"`: independent Beta priors for both arms,
#'   - `"power"`: power prior on the control arm, flat prior on treatment.
#' @param prior_args List of prior hyperparameters. The following elements are supported:
#'   - `a0`: Discount factor for historical control data (only used if `prior = "power"`).
#'   - `y_0`, `n_0`: Number of responses and total patients in the historical control data.
#'   - `a_base_c`, `b_base_c`: Shape parameters of the Beta prior for the control arm.
#'   - `a_base_t`, `b_base_t`: Shape parameters of the Beta prior for the treatment arm.
#'     - Defaults for all `a_base_*` and `b_base_*` values are 1 (i.e., flat prior).
#' @param n_draws Integer. Number of posterior draws per trial for estimating the probability.
#' @param show_progress Logical. Show progress bar in the console.
#'
#' @return A logical vector of length `B`, indicating for each trial whether the decision
#' criterion was met (i.e., trial declared successful).
#'
#' @details This function uses Rcpp and vectorized binomial simulation to increase speed.
#' Posterior samples are drawn from Beta distributions parameterized using either flat priors
#' or power priors (for control) combined with observed trial data.
#'
#' @examples
#' prior_args <- list(
#'   a0 = 0.5, y_0 = 20, n_0 = 30,
#'   a_base_c = 1, b_base_c = 1,
#'   a_base_t = 2, b_base_t = 2
#' )
#' decisions <- rct_power_beta_binom_cpp_vec(
#'   B = 1000, p_c = 0.8, p_t = 0.8,
#'   n_c = 25, n_t = 25,
#'   M = -0.1, threshold = 0.9,
#'   prior = "power", prior_args = prior_args,
#'   n_draws = 2000, show_progress = FALSE
#' )
#' mean(decisions)  # Estimated power
#'
#' @export
rct_power_beta_binom_cpp_vec <- function(B, p_c, p_t, n_c, n_t, M, threshold, prior, prior_args, n_draws, show_progress = TRUE) {
    .Call(`_bcts_rct_power_beta_binom_cpp_vec`, B, p_c, p_t, n_c, n_t, M, threshold, prior, prior_args, n_draws, show_progress)
}

beta_prob_gt <- function(a, b, M, n_draws) {
    .Call(`_bcts_beta_prob_gt`, a, b, M, n_draws)
}

#' @title Analytic Power Calculation for Single-Arm Beta-Binomial Design
#'
#' @description Computes the exact Bayesian power for a single-arm binomial trial with a
#' conjugate Beta prior. Power is defined as the probability that the posterior probability
#' that the true response rate exceeds a threshold \code{M} is greater than or equal to
#' a prespecified cutoff \code{threshold}, under a fixed true response rate \code{p_t}.
#'
#' This function avoids simulation and uses a deterministic summation over all possible
#' outcomes of the binomial distribution.
#'
#' @param p_t Numeric in \[0, 1\]. True response probability for the treatment arm.
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric in \[0, 1\]. Threshold on the response rate for decision-making,
#' e.g., \code{M = 0.6}.
#' @param threshold Numeric in \[0, 1\]. Posterior probability cutoff for declaring success,
#' e.g., \code{0.95}.
#' @param prior Character string specifying the prior distribution.
#' Options are:
#' "flat" for a non-informative Beta(1,1) prior;
#' "jeffreys" for the Jeffreys prior (Beta(0.5, 0.5));
#' "beta" for a custom Beta(\code{a_base}, \code{b_base}) prior (user must provide \code{a_base} and \code{b_base}).
#' @param a_base Numeric. Alpha parameter for the Beta prior (used only if \code{prior = "beta"}).
#' @param b_base Numeric. Beta parameter for the Beta prior (used only if \code{prior = "beta"}).
#'
#' @return A named list with:
#' \describe{
#'   \item{\code{estimate}}{The exact Bayesian power (a number between 0 and 1).}
#'   \item{\code{mc_se}}{\code{NA_real_}, returned for compatibility (Monte Carlo SE not applicable).}
#'   \item{\code{B}}{\code{NA_integer_}, returned for compatibility with simulation version.}
#'   \item{\code{successes}}{\code{NA_integer_}, returned for compatibility.}
#' }
#'
#' @examples
#' sat_betabinom_power_exact(
#'   p_t = 0.75, n_t = 35, M = 0.6,
#'   threshold = 0.95, prior = "flat"
#' )
#'
#' @seealso \code{\link{sat_betabinom_power}} for the simulation-based version.
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
sat_betabinom_power_exact <- function(p_t, n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1) {
    .Call(`_bcts_sat_betabinom_power_exact`, p_t, n_t, M, threshold, prior, a_base, b_base)
}

#' @title Compute p-values for a t-distribution with Fixed Degrees of Freedom
#'
#' @description Simulates a single-arm binomial trial with a conjugate Beta prior,
#' and computes the Bayesian power - the proportion of trials where the posterior
#' probability that the response rate exceeds a threshold \code{M} is greater than or equal
#' to a specified decision threshold.
#'
#' @param B Integer. Number of trial simulations.
#' @param p_t Numeric in \[0, 1\]. True response probability for the treatment arm.
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric in \[0, 1\]. Decision threshold on the response rate, e.g., \code{M = 0.6}.
#' @param threshold Numeric in \[0, 1\]. Posterior probability cutoff for declaring success,
#' e.g., \code{0.95}.
#' @param prior Character string specifying the prior distribution.
#' Options are:
#' "flat" for a non-informative Beta(1,1) prior;
#' "jeffreys" for the Jeffreys prior (Beta(0.5, 0.5));
#' "beta" for a custom Beta(\code{a_base}, \code{b_base}) prior (user must provide \code{a_base} and \code{b_base}).
#' @param a_base Numeric. Alpha parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param b_base Numeric. Beta parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param show_progress Logical. If \code{TRUE}, prints a simple progress bar to console.
#'
#' @return A list with: estimate (power), mc_se, successes, B.
#'
#' @examples
#' sat_betabinom_power(
#'   B = 1000, p_t = 0.75, n_t = 35, M = 0.60,
#'   threshold = 0.95, prior = "flat"
#' )
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
sat_betabinom_power <- function(B, p_t, n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1, show_progress = TRUE) {
    .Call(`_bcts_sat_betabinom_power`, B, p_t, n_t, M, threshold, prior, a_base, b_base, show_progress)
}

#' @title Estimate Type-I Error for Single-Arm Trial
#'
#' @description Simulates a single-arm binomial trial under the null hypothesis,
#' and computes the type-I error: the proportion of simulations where posterior
#' Pr(θ > M) ≥ threshold even though θ = p_null.
#'
#' @param B Integer. Number of simulations.
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric. Decision threshold for θ (on probability scale, e.g., 0.6).
#' @param threshold Posterior probability threshold γ (e.g., 0.95).
#' @param prior Character string specifying the prior distribution.
#' Options are:
#' "flat" for a non-informative Beta(1,1) prior;
#' "jeffreys" for the Jeffreys prior (Beta(0.5, 0.5));
#' "beta" for a custom Beta(\code{a_base}, \code{b_base}) prior (user must provide \code{a_base} and \code{b_base}).
#' @param a_base Alpha parameter for Beta prior (if prior = "beta").
#' @param b_base Beta parameter for Beta prior (if prior = "beta").
#' @param show_progress Logical. Show progress in console?
#'
#' @return A list with \code{estimate} (type-I error), \code{mc_se}, \code{B}, and \code{rejections}.
#'
#' @examples
#' sat_betabinom_type1(
#'   B = 1000, n_t = 35, M = 0.6,
#'   threshold = 0.95, prior = "flat"
#' )
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
sat_betabinom_type1 <- function(B, n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1, show_progress = TRUE) {
    .Call(`_bcts_sat_betabinom_type1`, B, n_t, M, threshold, prior, a_base, b_base, show_progress)
}

#' @title Exact Type-I Error for Single-Arm Trial (Beta-Binomial)
#'
#' @description Computes the exact Type-I error for a single-arm binomial trial
#' using a conjugate Beta prior. This is done by summing the probability of all
#' outcomes where the posterior probability that \eqn{\theta > M} exceeds a
#' decision threshold \code{threshold}, under the null hypothesis.
#'
#' By default, the null hypothesis is \eqn{\theta = M}, but a more conservative
#' frequentist setting can be evaluated by setting \code{p_null < M}.
#'
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric in \[0, 1\]. Decision threshold on the response rate, e.g., \code{M = 0.6}.
#' @param threshold Numeric in \[0, 1\]. Posterior probability cutoff for declaring success,
#' e.g., \code{threshold = 0.95}.
#' @param prior Character string specifying the prior distribution.
#' Options are:
#' "flat" for a non-informative Beta(1,1) prior;
#' "jeffreys" for the Jeffreys prior (Beta(0.5, 0.5));
#' "beta" for a custom Beta(\code{a_base}, \code{b_base}) prior (user must provide \code{a_base} and \code{b_base})..
#' @param a_base Numeric. Alpha parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param b_base Numeric. Beta parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param p_null Optional. True response probability under the null hypothesis (e.g., \code{p_null = 0.6}).
#' If not specified, defaults to \code{p_null = M} (boundary case).
#'
#' @return A named list with:
#' \describe{
#'   \item{\code{estimate}}{Exact Type-I error (a number between 0 and 1).}
#'   \item{\code{mc_se}}{\code{NA_real_}, included for compatibility.}
#'   \item{\code{B}}{\code{NA_integer_}, included for compatibility.}
#'   \item{\code{rejections}}{\code{NA_integer_}, included for compatibility.}
#' }
#'
#' @examples
#' # Type-I error under flat prior at boundary
#' sat_betabinom_type1_exact(n_t = 40, M = 0.65, threshold = 0.9, prior = "flat")
#'
#' # Type-I error under true p < M (frequentist view)
#' sat_betabinom_type1_exact(n_t = 40, M = 0.65, threshold = 0.9,
#'                            prior = "flat", p_null = 0.60)
#'
#' @seealso \code{\link{sat_betabinom_type1}} for the simulation-based version.
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
sat_betabinom_type1_exact <- function(n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1, p_null = -1.0) {
    .Call(`_bcts_sat_betabinom_type1_exact`, n_t, M, threshold, prior, a_base, b_base, p_null)
}

