# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_prob_gt <- function(a, b, M, n_draws) {
    .Call(`_bcts_beta_prob_gt`, a, b, M, n_draws)
}

#' @title Compute p-values for a t-distribution with Fixed Degrees of Freedom
#'
#' @description Simulates a single-arm binomial trial with a conjugate Beta prior,
#' and computes the Bayesian power - the proportion of trials where the posterior
#' probability that the response rate exceeds a threshold \code{M} is greater than or equal
#' to a specified decision threshold.
#'
#' @param B Integer. Number of trial simulations.
#' @param p_t Numeric in \[0, 1\]. True response probability for the treatment arm.
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric in \[0, 1\]. Decision threshold on the response rate, e.g., \code{M = 0.6}.
#' @param threshold Numeric in \[0, 1\]. Posterior probability cutoff for declaring success,
#' e.g., \code{0.95}.
#' @param prior Character string. Either \code{"flat"} for a Beta(1,1) prior or
#' \code{"beta"} to specify a custom prior using \code{a_base} and \code{b_base}.
#' @param a_base Numeric. Alpha parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param b_base Numeric. Beta parameter for the Beta prior (only used if \code{prior = "beta"}).
#' @param n_draws Integer. Number of posterior draws per trial.
#' @param show_progress Logical. If \code{TRUE}, prints a simple progress bar to console.
#'
#' @return A list with: estimate (power), mc_se, successes, B.
#'
#' @examples
#' singlearm_beta_power(
#'   B = 1000, p_t = 0.75, n_t = 35, M = 0.60,
#'   threshold = 0.95, prior = "flat", n_draws = 2000
#' )
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
singlearm_beta_power <- function(B, p_t, n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1, n_draws = 2000L, show_progress = TRUE) {
    .Call(`_bcts_singlearm_beta_power`, B, p_t, n_t, M, threshold, prior, a_base, b_base, n_draws, show_progress)
}

#' @title Estimate Type-I Error for Single-Arm Trial
#'
#' @description Simulates a single-arm binomial trial under the null hypothesis,
#' and computes the type-I error: the proportion of simulations where posterior
#' Pr(θ > M) ≥ threshold even though θ = p_null.
#'
#' @param B Integer. Number of simulations.
#' @param n_t Integer. Sample size of the treatment arm.
#' @param M Numeric. Decision threshold for θ (on probability scale, e.g., 0.6).
#' @param threshold Posterior probability threshold γ (e.g., 0.95).
#' @param prior "flat" or "beta".
#' @param a_base Alpha parameter for Beta prior (if prior = "beta").
#' @param b_base Beta parameter for Beta prior (if prior = "beta").
#' @param n_draws Number of posterior draws per trial.
#' @param show_progress Logical. Show progress in console?
#'
#' @return A list with \code{estimate} (type-I error), \code{mc_se}, \code{B}, and \code{rejections}.
#'
#' @examples
#' singlearm_beta_type1(
#'   B = 1000, n_t = 35, M = 0.6,
#'   threshold = 0.95, prior = "flat", n_draws = 2000
#' )
#'
#' @author Thomas Debray \email{tdebray@fromdatatowisdom.com}
#' @export
singlearm_beta_type1 <- function(B, n_t, M, threshold, prior = "flat", a_base = 1, b_base = 1, n_draws = 2000L, show_progress = TRUE) {
    .Call(`_bcts_singlearm_beta_type1`, B, n_t, M, threshold, prior, a_base, b_base, n_draws, show_progress)
}

